/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentesDeIaRouteImport } from './routes/agentes-de-ia'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as EquipeDeDadosRouteImport } from './routes/equipe-de-dados'
import { Route as MetodoRouteImport } from './routes/metodo'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentesDeIaRoute = AgentesDeIaRouteImport.update({
  id: '/agentes-de-ia',
  path: '/agentes-de-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeDeDadosRoute = EquipeDeDadosRouteImport.update({
  id: '/equipe-de-dados',
  path: '/equipe-de-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoRoute = MetodoRouteImport.update({
  id: '/metodo',
  path: '/metodo',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agentes-de-ia': typeof AgentesDeIaRoute
  '/contato': typeof ContatoRoute
  '/equipe-de-dados': typeof EquipeDeDadosRoute
  '/metodo': typeof MetodoRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/solucoes': typeof SolucoesRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agentes-de-ia': typeof AgentesDeIaRoute
  '/contato': typeof ContatoRoute
  '/equipe-de-dados': typeof EquipeDeDadosRoute
  '/metodo': typeof MetodoRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/solucoes': typeof SolucoesRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agentes-de-ia': typeof AgentesDeIaRoute
  '/contato': typeof ContatoRoute
  '/equipe-de-dados': typeof EquipeDeDadosRoute
  '/metodo': typeof MetodoRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/solucoes': typeof SolucoesRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agentes-de-ia'
    | '/contato'
    | '/equipe-de-dados'
    | '/metodo'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/solucoes'
    | '/termos-de-uso'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agentes-de-ia'
    | '/contato'
    | '/equipe-de-dados'
    | '/metodo'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/solucoes'
    | '/termos-de-uso'
  id:
    | '__root__'
    | '/'
    | '/agentes-de-ia'
    | '/contato'
    | '/equipe-de-dados'
    | '/metodo'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/solucoes'
    | '/termos-de-uso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentesDeIaRoute: typeof AgentesDeIaRoute
  ContatoRoute: typeof ContatoRoute
  EquipeDeDadosRoute: typeof EquipeDeDadosRoute
  MetodoRoute: typeof MetodoRoute
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SolucoesRoute: typeof SolucoesRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentes-de-ia': {
      id: '/agentes-de-ia'
      path: '/agentes-de-ia'
      fullPath: '/agentes-de-ia'
      preLoaderRoute: typeof AgentesDeIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe-de-dados': {
      id: '/equipe-de-dados'
      path: '/equipe-de-dados'
      fullPath: '/equipe-de-dados'
      preLoaderRoute: typeof EquipeDeDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo': {
      id: '/metodo'
      path: '/metodo'
      fullPath: '/metodo'
      preLoaderRoute: typeof MetodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentesDeIaRoute: AgentesDeIaRoute,
  ContatoRoute: ContatoRoute,
  EquipeDeDadosRoute: EquipeDeDadosRoute,
  MetodoRoute: MetodoRoute,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SolucoesRoute: SolucoesRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
