/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentesDeIaRouteImport } from './routes/agentes-de-ia'
import { Route as CartaoRouteImport } from './routes/cartao'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as EquipeDeDadosRouteImport } from './routes/equipe-de-dados'
import { Route as MetodoRouteImport } from './routes/metodo'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as SejaUmRepresentanteComercialRouteImport } from './routes/seja-um-representante-comercial'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as SolucoesIndexRouteImport } from './routes/solucoes.index'
import { Route as SolucoesBiDataQualityRouteImport } from './routes/solucoes.bi-data-quality'
import { Route as SolucoesBiIaOutsourcingRouteImport } from './routes/solucoes.bi-ia-outsourcing'
import { Route as SolucoesBiPlatformRouteImport } from './routes/solucoes.bi-platform'
import { Route as SolucoesBusinessIntelligenceRouteImport } from './routes/solucoes.business-intelligence'
import { Route as SolucoesDataConsultingRouteImport } from './routes/solucoes.data-consulting'
import { Route as ApiPublicCytrixContactDotvcfRouteImport } from './routes/api/public/cytrix-contact[.]vcf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentesDeIaRoute = AgentesDeIaRouteImport.update({
  id: '/agentes-de-ia',
  path: '/agentes-de-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const CartaoRoute = CartaoRouteImport.update({
  id: '/cartao',
  path: '/cartao',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeDeDadosRoute = EquipeDeDadosRouteImport.update({
  id: '/equipe-de-dados',
  path: '/equipe-de-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoRoute = MetodoRouteImport.update({
  id: '/metodo',
  path: '/metodo',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const SejaUmRepresentanteComercialRoute =
  SejaUmRepresentanteComercialRouteImport.update({
    id: '/seja-um-representante-comercial',
    path: '/seja-um-representante-comercial',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesIndexRoute = SolucoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SolucoesRoute,
} as any)
const SolucoesBiDataQualityRoute = SolucoesBiDataQualityRouteImport.update({
  id: '/bi-data-quality',
  path: '/bi-data-quality',
  getParentRoute: () => SolucoesRoute,
} as any)
const SolucoesBiIaOutsourcingRoute = SolucoesBiIaOutsourcingRouteImport.update({
  id: '/bi-ia-outsourcing',
  path: '/bi-ia-outsourcing',
  getParentRoute: () => SolucoesRoute,
} as any)
const SolucoesBiPlatformRoute = SolucoesBiPlatformRouteImport.update({
  id: '/bi-platform',
  path: '/bi-platform',
  getParentRoute: () => SolucoesRoute,
} as any)
const SolucoesBusinessIntelligenceRoute =
  SolucoesBusinessIntelligenceRouteImport.update({
    id: '/business-intelligence',
    path: '/business-intelligence',
    getParentRoute: () => SolucoesRoute,
  } as any)
const SolucoesDataConsultingRoute = SolucoesDataConsultingRouteImport.update({
  id: '/data-consulting',
  path: '/data-consulting',
  getParentRoute: () => SolucoesRoute,
} as any)
const ApiPublicCytrixContactDotvcfRoute =
  ApiPublicCytrixContactDotvcfRouteImport.update({
    id: '/api/public/cytrix-contact.vcf',
    path: '/api/public/cytrix-contact.vcf',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agentes-de-ia': typeof AgentesDeIaRoute
  '/cartao': typeof CartaoRoute
  '/contato': typeof ContatoRoute
  '/equipe-de-dados': typeof EquipeDeDadosRoute
  '/metodo': typeof MetodoRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/seja-um-representante-comercial': typeof SejaUmRepresentanteComercialRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solucoes': typeof SolucoesRouteWithChildren
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/solucoes/bi-data-quality': typeof SolucoesBiDataQualityRoute
  '/solucoes/bi-ia-outsourcing': typeof SolucoesBiIaOutsourcingRoute
  '/solucoes/bi-platform': typeof SolucoesBiPlatformRoute
  '/solucoes/business-intelligence': typeof SolucoesBusinessIntelligenceRoute
  '/solucoes/data-consulting': typeof SolucoesDataConsultingRoute
  '/solucoes/': typeof SolucoesIndexRoute
  '/api/public/cytrix-contact.vcf': typeof ApiPublicCytrixContactDotvcfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agentes-de-ia': typeof AgentesDeIaRoute
  '/cartao': typeof CartaoRoute
  '/contato': typeof ContatoRoute
  '/equipe-de-dados': typeof EquipeDeDadosRoute
  '/metodo': typeof MetodoRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/seja-um-representante-comercial': typeof SejaUmRepresentanteComercialRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/solucoes/bi-data-quality': typeof SolucoesBiDataQualityRoute
  '/solucoes/bi-ia-outsourcing': typeof SolucoesBiIaOutsourcingRoute
  '/solucoes/bi-platform': typeof SolucoesBiPlatformRoute
  '/solucoes/business-intelligence': typeof SolucoesBusinessIntelligenceRoute
  '/solucoes/data-consulting': typeof SolucoesDataConsultingRoute
  '/solucoes': typeof SolucoesIndexRoute
  '/api/public/cytrix-contact.vcf': typeof ApiPublicCytrixContactDotvcfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agentes-de-ia': typeof AgentesDeIaRoute
  '/cartao': typeof CartaoRoute
  '/contato': typeof ContatoRoute
  '/equipe-de-dados': typeof EquipeDeDadosRoute
  '/metodo': typeof MetodoRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/seja-um-representante-comercial': typeof SejaUmRepresentanteComercialRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solucoes': typeof SolucoesRouteWithChildren
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/solucoes/bi-data-quality': typeof SolucoesBiDataQualityRoute
  '/solucoes/bi-ia-outsourcing': typeof SolucoesBiIaOutsourcingRoute
  '/solucoes/bi-platform': typeof SolucoesBiPlatformRoute
  '/solucoes/business-intelligence': typeof SolucoesBusinessIntelligenceRoute
  '/solucoes/data-consulting': typeof SolucoesDataConsultingRoute
  '/solucoes/': typeof SolucoesIndexRoute
  '/api/public/cytrix-contact.vcf': typeof ApiPublicCytrixContactDotvcfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agentes-de-ia'
    | '/cartao'
    | '/contato'
    | '/equipe-de-dados'
    | '/metodo'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/quem-somos'
    | '/seja-um-representante-comercial'
    | '/sitemap.xml'
    | '/solucoes'
    | '/termos-de-uso'
    | '/solucoes/bi-data-quality'
    | '/solucoes/bi-ia-outsourcing'
    | '/solucoes/bi-platform'
    | '/solucoes/business-intelligence'
    | '/solucoes/data-consulting'
    | '/solucoes/'
    | '/api/public/cytrix-contact.vcf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agentes-de-ia'
    | '/cartao'
    | '/contato'
    | '/equipe-de-dados'
    | '/metodo'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/quem-somos'
    | '/seja-um-representante-comercial'
    | '/sitemap.xml'
    | '/termos-de-uso'
    | '/solucoes/bi-data-quality'
    | '/solucoes/bi-ia-outsourcing'
    | '/solucoes/bi-platform'
    | '/solucoes/business-intelligence'
    | '/solucoes/data-consulting'
    | '/solucoes'
    | '/api/public/cytrix-contact.vcf'
  id:
    | '__root__'
    | '/'
    | '/agentes-de-ia'
    | '/cartao'
    | '/contato'
    | '/equipe-de-dados'
    | '/metodo'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/quem-somos'
    | '/seja-um-representante-comercial'
    | '/sitemap.xml'
    | '/solucoes'
    | '/termos-de-uso'
    | '/solucoes/bi-data-quality'
    | '/solucoes/bi-ia-outsourcing'
    | '/solucoes/bi-platform'
    | '/solucoes/business-intelligence'
    | '/solucoes/data-consulting'
    | '/solucoes/'
    | '/api/public/cytrix-contact.vcf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentesDeIaRoute: typeof AgentesDeIaRoute
  CartaoRoute: typeof CartaoRoute
  ContatoRoute: typeof ContatoRoute
  EquipeDeDadosRoute: typeof EquipeDeDadosRoute
  MetodoRoute: typeof MetodoRoute
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  QuemSomosRoute: typeof QuemSomosRoute
  SejaUmRepresentanteComercialRoute: typeof SejaUmRepresentanteComercialRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolucoesRoute: typeof SolucoesRouteWithChildren
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  ApiPublicCytrixContactDotvcfRoute: typeof ApiPublicCytrixContactDotvcfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentes-de-ia': {
      id: '/agentes-de-ia'
      path: '/agentes-de-ia'
      fullPath: '/agentes-de-ia'
      preLoaderRoute: typeof AgentesDeIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartao': {
      id: '/cartao'
      path: '/cartao'
      fullPath: '/cartao'
      preLoaderRoute: typeof CartaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe-de-dados': {
      id: '/equipe-de-dados'
      path: '/equipe-de-dados'
      fullPath: '/equipe-de-dados'
      preLoaderRoute: typeof EquipeDeDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo': {
      id: '/metodo'
      path: '/metodo'
      fullPath: '/metodo'
      preLoaderRoute: typeof MetodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seja-um-representante-comercial': {
      id: '/seja-um-representante-comercial'
      path: '/seja-um-representante-comercial'
      fullPath: '/seja-um-representante-comercial'
      preLoaderRoute: typeof SejaUmRepresentanteComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/': {
      id: '/solucoes/'
      path: '/'
      fullPath: '/solucoes/'
      preLoaderRoute: typeof SolucoesIndexRouteImport
      parentRoute: typeof SolucoesRoute
    }
    '/solucoes/bi-data-quality': {
      id: '/solucoes/bi-data-quality'
      path: '/bi-data-quality'
      fullPath: '/solucoes/bi-data-quality'
      preLoaderRoute: typeof SolucoesBiDataQualityRouteImport
      parentRoute: typeof SolucoesRoute
    }
    '/solucoes/bi-ia-outsourcing': {
      id: '/solucoes/bi-ia-outsourcing'
      path: '/bi-ia-outsourcing'
      fullPath: '/solucoes/bi-ia-outsourcing'
      preLoaderRoute: typeof SolucoesBiIaOutsourcingRouteImport
      parentRoute: typeof SolucoesRoute
    }
    '/solucoes/bi-platform': {
      id: '/solucoes/bi-platform'
      path: '/bi-platform'
      fullPath: '/solucoes/bi-platform'
      preLoaderRoute: typeof SolucoesBiPlatformRouteImport
      parentRoute: typeof SolucoesRoute
    }
    '/solucoes/business-intelligence': {
      id: '/solucoes/business-intelligence'
      path: '/business-intelligence'
      fullPath: '/solucoes/business-intelligence'
      preLoaderRoute: typeof SolucoesBusinessIntelligenceRouteImport
      parentRoute: typeof SolucoesRoute
    }
    '/solucoes/data-consulting': {
      id: '/solucoes/data-consulting'
      path: '/data-consulting'
      fullPath: '/solucoes/data-consulting'
      preLoaderRoute: typeof SolucoesDataConsultingRouteImport
      parentRoute: typeof SolucoesRoute
    }
    '/api/public/cytrix-contact.vcf': {
      id: '/api/public/cytrix-contact.vcf'
      path: '/api/public/cytrix-contact.vcf'
      fullPath: '/api/public/cytrix-contact.vcf'
      preLoaderRoute: typeof ApiPublicCytrixContactDotvcfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SolucoesRouteChildren {
  SolucoesBiDataQualityRoute: typeof SolucoesBiDataQualityRoute
  SolucoesBiIaOutsourcingRoute: typeof SolucoesBiIaOutsourcingRoute
  SolucoesBiPlatformRoute: typeof SolucoesBiPlatformRoute
  SolucoesBusinessIntelligenceRoute: typeof SolucoesBusinessIntelligenceRoute
  SolucoesDataConsultingRoute: typeof SolucoesDataConsultingRoute
  SolucoesIndexRoute: typeof SolucoesIndexRoute
}

const SolucoesRouteChildren: SolucoesRouteChildren = {
  SolucoesBiDataQualityRoute: SolucoesBiDataQualityRoute,
  SolucoesBiIaOutsourcingRoute: SolucoesBiIaOutsourcingRoute,
  SolucoesBiPlatformRoute: SolucoesBiPlatformRoute,
  SolucoesBusinessIntelligenceRoute: SolucoesBusinessIntelligenceRoute,
  SolucoesDataConsultingRoute: SolucoesDataConsultingRoute,
  SolucoesIndexRoute: SolucoesIndexRoute,
}

const SolucoesRouteWithChildren = SolucoesRoute._addFileChildren(
  SolucoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentesDeIaRoute: AgentesDeIaRoute,
  CartaoRoute: CartaoRoute,
  ContatoRoute: ContatoRoute,
  EquipeDeDadosRoute: EquipeDeDadosRoute,
  MetodoRoute: MetodoRoute,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  QuemSomosRoute: QuemSomosRoute,
  SejaUmRepresentanteComercialRoute: SejaUmRepresentanteComercialRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolucoesRoute: SolucoesRouteWithChildren,
  TermosDeUsoRoute: TermosDeUsoRoute,
  ApiPublicCytrixContactDotvcfRoute: ApiPublicCytrixContactDotvcfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
